### ISSUE TITLE
Caching wp-admin users content

### ISSUE THREAD

**Issue by andreasgan** [bcc-code/bcc-wp-proxy#2]
https://proxy.frabegynnelsen.no/brev/brev-40-17-februar-1907-horten/
![image](https://user-images.githubusercontent.com/727125/112730481-18ac1680-8f32-11eb-9e59-cb2c2d56007c.png)

**Comment by rvanoord** [comment]
This problem turned out to be an incompatibility issue with the WP Rocket plugin. This issue is strictly speaking part of the bcc-wp-proxy WordPress plugin, (rather than the bcc-wp-proxy cache _server_), because the mechanism used to authenticate users in WP is not being picked up by WP Rocket. Perhaps its coming too late?

One solution could be to add the Asp.Net session cookie to the WP Rocket "Never cache cookies" list:
https://docs.wp-rocket.me/article/313-user-cache
